# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 20.04'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar Cloud IO'
    organization: 'upfrance'
    scannerMode: 'CLI'
    configMode: 'file'
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
- script: |
    npm i
    npm build
    npm test
    npm run build-storybook
  displayName: 'npm install and publish static site'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: CopyFiles@2
  inputs:
    sourceFolder: public
    contents: '**' 
    targetFolder: $(Build.ArtifactStagingDirectory) 
    cleanTargetFolder: true
- task: CopyFiles@2
  inputs:
    sourceFolder: infrastructure
    contents: '**' 
    targetFolder: $(Build.ArtifactStagingDirectory) 
    cleanTargetFolder: false
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: site
    publishLocation: Container
    targetPath:
